name: Bug Report
description: Create a report to help us improve our resource.
title: "Bug: <short description>"
labels: New Issue

body:
- type: markdown
  attributes:
    value: |
      ## Thank you for filling out this bug report
      Please fill out this short template to the best of your ability.
- type: dropdown
  id: developement-issue
  attributes:
    label: Developement Issue
    description: Is this issue related to the phone still being in development?
    options:
      - "Yes"
      - "No"
      - Unsure
  validations:
      required: true
- type: textarea
  id: issue-description
  attributes:
    label: Issue Description
    description: A clear and concise description of what the issue is. Ommit reproduction steps.
  validations:
    required: true
 - type: markdown
  attributes:
    value: |
    Brr?
    ```
     1. Go to '...'
     2. Click on '....'
     3. Scroll down to '....'
     4. See error
    ```
- type: textarea
  id: issue-reproduction
  validations:
    required: false
